### ISSUE TITLE
Green  Power LED

### ISSUE THREAD

**Issue by webpilot101** [rperciaccante/MopekaLCDDisplay#10]
Can the green LED and red LED on the back be turned off?   I would like to turn the LEDs off through software at least at night, if not longer.

**Comment by rperciaccante** [comment]
Unfortunately there is no GPIO attached to that LED from the manufacturer, so I am not able to turn it on or off.  The 3D printed case included in the repo covers the LED's so that they are not visible (if you print the reset button in clear resin you can see just a little light for status)
